// SPDX-License-Identifier: MIT
// Gearbox Protocol. Generalized leverage for DeFi protocols
// (c) Gearbox Foundation, 2024.
pragma solidity ^0.8.17;

bytes32 constant AP_MARKET_COMPRESSOR = "MARKET_COMPRESSOR";
bytes32 constant AP_POOL_COMPRESSOR = "POOL_COMPRESSOR";
bytes32 constant AP_TOKEN_COMPRESSOR = "TOKEN_COMPRESSOR";
bytes32 constant AP_PRICE_FEED_COMPRESSOR = "PRICE_FEED_COMPRESSOR";
bytes32 constant AP_CREDIT_ACCOUNT_COMPRESSOR = "CREDIT_ACCOUNT_COMPRESSOR";
bytes32 constant AP_CREDIT_SUITE_COMPRESSOR = "CREDIT_SUITE_COMPRESSOR";
bytes32 constant AP_PERIPHERY_COMPRESSOR = "PERIPHERY_COMPRESSOR";
bytes32 constant AP_ADAPTER_COMPRESSOR = "ADAPTER_COMPRESSOR";
bytes32 constant AP_REWARDS_COMPRESSOR = "REWARDS_COMPRESSOR";
bytes32 constant AP_GAUGE_COMPRESSOR = "GAUGE_COMPRESSOR";
